openapi: 3.0.0

paths:
  /api/v1/clients:
    # Create client
    post:
      security:
        - bearerAuth: []
      tags:
        - Client
      description: Create a client
      operationId: CreateClient
      summary: Create a client
      requestBody:
        $ref: "#/components/requestBodies/CreateClientRequestBody"
      responses:
        201:
          $ref: "#/components/responses/201CreateClientSuccess"
        400:
          $ref: "#/components/responses/BadRequestResponse"
        401:
          $ref: "#/components/responses/UnauthorizedResponse"
        403:
          $ref: "#/components/responses/ForbiddenResponse"
        404:
          $ref: "#/components/responses/NotFoundResponse"
        500:
          $ref: "#/components/responses/InternalServerErrorResponse"
        501:
          $ref: "#/components/responses/NotImplementedResponse"
        502:
          $ref: "#/components/responses/BadGatewayResponse"
        503:
          $ref: "#/components/responses/ServiceUnavailableResponse"
        504:
          $ref: "#/components/responses/GatewayTimeoutResponse"

