openapi: 3.0.0

components:
  schemas:
    Client:
      type: object
      properties:
        name:
          type: string
          description: client name
          example: lirest-user-service
        description:
          type: string
          description: client description
          example: lirest user service
        resources:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: resource name
                example: user
              attributes:
                type: array
                items:
                  type: string
                  description: attribute name
                  example: name
              actions:
                type: array
                items:
                  type: string
                  description: action name
                  example: read
  requestBodies:
    CreateClientRequestBody:
      description: client data
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Client"
  responses:
    201CreateClientSuccess:
      description: Create client successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Client'
    200UpdateClientSuccess:
      description: Update client successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
