openapi: 3.0.0

components:
  schemas:
    Subject:
      type: object
      properties:
        subjectId:
          type: string
          description: subject id
          example: q9mjc8li77
        name:
          type: string
          description: subject name
          example: admin
        type:
          type: string
          description: subject type
          example: user, group, role
        description:
          type: string
          description: subject description
          example: api endpoint subject
  requestBodies:
    CreateSubjectRequestBody:
      description: subject data
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Subject"
  responses:
    201CreateSubjectSuccess:
      description: Create subject successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Subject'
    200UpdateSubjectSuccess:
      description: Update subject successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
    200GetAllSubjectsSuccess:
      description: Get all subjects successfully
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Subject'
