version: '3.8'

services:
 lirest-iam:
  container_name: lirest-iam
  build:
   context: .
   dockerfile: Dockerfile
  image: lirest-iam:latest
  restart: unless-stopped
  env_file: .env
  environment:
   - MONGODB_URI=${MONGODB_URI}
  ports:
   - "3030:3030"
  volumes:
   - .:/home/node/app
   - node_modules:/home/node/app/node_modules
  networks:
   - app-network

 mongo:
  image: mongo:latest
  container_name: mongo
  restart: unless-stopped
  env_file: .env
  environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  volumes:
    - dbdata:/data/db
  networks:
    - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:
