openapi: 3.0.0

components:
  schemas:
    Role:
      type: object
      properties:
        name:
          type: string
          description: role name
          example: admin
        description:
          type: string
          description: role description
          example: admin role
        permission:
          type: object
          properties:
            subject:
              type: string
              description: subject name
              example: user
            action:
              type: string
              description: action name
              example: read
            conditions:
              type: object
              description: conditions
              example: {}
  parameters:
    RoleId:
      name: id
      in: path
      description: Role id
      required: true
      schema:
        type: string
        example: 5f9f1b9b9c9b8c0b8c8b9b9b
  requestBodies:
    CreateRoleRequestBody:
      description: Role data
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Role"
    AssignPermissionsToRoleByIdRequestBody:
      description: Permission data
      required: true
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                subject:
                  type: string
                  description: permission name
                  example: user
                action:
                  type: string
                  description: permission value
                  example: read
                conditions:
                  type: object
                  description: permission conditions
                  example: {}
  responses:
    201CreateRoleSuccess:
      description: Create role successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
    200UpdateRoleSuccess:
      description: Update role successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
    200GetRolesSuccess:
      description: Get roles successfully
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Role'
    200AssignPermissionsToRoleByIdSuccess:
      description: Assign permissions to role by id successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
