openapi: 3.0.0

paths:
  /api/v1/roles:
    # Create role
    post:
      security:
        - bearerAuth: []
      tags:
        - Role
      description: Create a role
      operationId: CreateRole
      summary: Create a role
      requestBody:
        $ref: "#/components/requestBodies/CreateRoleRequestBody"
      responses:
        201:
          $ref: "#/components/responses/201CreateRoleSuccess"
        400:
          $ref: "#/components/responses/BadRequestResponse"
        401:
          $ref: "#/components/responses/UnauthorizedResponse"
        403:
          $ref: "#/components/responses/ForbiddenResponse"
        404:
          $ref: "#/components/responses/NotFoundResponse"
        500:
          $ref: "#/components/responses/InternalServerErrorResponse"
        501:
          $ref: "#/components/responses/NotImplementedResponse"
        502:
          $ref: "#/components/responses/BadGatewayResponse"
        503:
          $ref: "#/components/responses/ServiceUnavailableResponse"
        504:
          $ref: "#/components/responses/GatewayTimeoutResponse"

