# Service configuration
service:
  name: lirest-iam
  host: HOST_NAME
  port: SERVICE_PORT
  baseUrl: SERVICE_BASE_URL

# Database configuration
mongodb:
  uri: MONGODB_URI

# API documentation configuration
api-docs:
  username: API_DOCS_USERNAME
  password: API_DOCS_PASSWORD

# Log configuration
log:
  level: LOG_LEVEL

# JWT configuration
jwt:
  accessTokenKey: ACCESS_TOKEN_KEY
  refreshTokenKey: REFRESH_TOKEN_KEY
  accessTokenExpiresIn: ACCESS_TOKEN_EXPIRES_IN
  refreshTokenExpiresIn: REFRESH_TOKEN_EXPIRES_IN

# Kafka configuration
kafka:
  clientId: KAFKA_CLIENT_ID
  groupId: KAFKA_GROUP_ID
  serverUrl: KAFKA_SERVER_URL
  sasl:
    username: KAFKA_SASL_USERNAME
    password: KAFKA_SASL_PASSWORD
  enabled: KAFKA_ENABLED