# Service config
service:
  host: 127.0.0.1
  port: 3030
  baseUrl: /api/v1/iam

# Database configuration
mongodb:
  uri: mongodb://localhost:27017/lirest

# Swagger username and password
api-docs:
  username: ''
  password: ''

# Log configuration
log:
  level: info

# JWT config
jwt:
  accessTokenKey: Yp3s6v8y/B?E(H+MbQeThWmZq4t7w!z$
  refreshTokenKey: gUkXp2s5v8x/A?D(G+KbPeShVmYq3t6w
  accessTokenExpiresIn: 1h
  refreshTokenExpiresIn: 1d
